<?php

namespace AppBundle\Repository;

/**
 * CareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareRepository extends \Doctrine\ORM\EntityRepository
{
}
