<?php

namespace AppBundle\Repository;

/**
 * ConditionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsRepository extends \Doctrine\ORM\EntityRepository
{
}
