<?php

namespace AppBundle\Repository;

/**
 * EpisodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodesRepository extends \Doctrine\ORM\EntityRepository
{
}
