<?php

namespace AppBundle\Repository;

/**
 * GeneticCounsellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneticCounsellingRepository extends \Doctrine\ORM\EntityRepository
{
}
