<?php

namespace AppBundle\Repository;

/**
 * LabRadiologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabRadiologyRepository extends \Doctrine\ORM\EntityRepository
{
}
