<?php

namespace AppBundle\Repository;

/**
 * MedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedsRepository extends \Doctrine\ORM\EntityRepository
{
}
