<?php

namespace AppBundle\Repository;

/**
 * PatientStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
