<?php

namespace AppBundle\Repository;

/**
 * ReferralsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferralsRepository extends \Doctrine\ORM\EntityRepository
{
}
