<?php

namespace AppBundle\Repository;

/**
 * SurgicalHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurgicalHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
